# More NumPy Practice

Sometimes, there are more advanced operations we want to do with NumPy arrays. For example, if we had an array of values and wanted to set all negative values to zero, how would we do this? The answer is called *fancy indexing*, and be done two ways: boolean indexing, and array indexing.

In [1]:
import numpy as np

## Boolean indexing

The idea behind boolean indexing is that for each element of the array, we know whether we want to select it or not. A *boolean array* is an array of the same shape as our original array which contains only True and False values. The location of the True values in our boolean array indicate the location of the element in our original array that we want to select, while the location of the False values correspond to those elements in our original array that we _don't_ want to select.

Let's consider some experiment data. The details of the experiment aren't important here but just that we have an array of numbers that we'll interpret lightly and use for demonstration purposes.

In [2]:
data = np.load("experiment_data.npy")
data

array([[1668.07869346,  774.38921876, 3161.14983152, ..., 2359.05394666,
         784.36404676,  448.33416341],
       [2419.38185232,  809.18389145, 2766.62648929, ..., 1159.47379735,
        1330.44887992, 1842.3268586 ],
       [2221.02887591, 1496.00517071,  354.95889145, ..., 1355.74575912,
        1205.29137942, 1385.71283365],
       ...,
       [1654.50469248,  518.3271927 , 5127.58599224, ..., 2544.1042064 ,
         624.07607332, 1029.57386246],
       [ 480.68016502, 4690.12200498, 1520.27397139, ..., 1000.40541618,
         988.73647145,  378.43452948],
       [1823.42891807, 3680.12951133, 3522.94413167, ...,  591.4133153 ,
         383.26367525, 1768.50528483]])

In [3]:
data.shape

(50, 300)

These are reaction times for an experiment in milliseconds. It is typically accepted that really low reaction times -- such as less than 100 milliseconds -- are too fast for people to have actually seen and processed the stimulus. Let's see if there are any reaction times less than 100 milliseconds in our data.

To pull out just the elements less than 100 milliseconds, we need two steps. First, we use boolean comparisons to check which are less than 100ms:

In [4]:
too_fast = data < 100
too_fast

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

Then, using this `too_fast` array, we can index *back into* the original array, and see that there are indeed some trials which were abnormally fast:

In [5]:
data[too_fast]

array([86.28125135, 76.63231393, 68.72526177, 77.25801031, 97.065495  ,
       92.13792056, 90.05066503, 86.59892207, 96.45674184, 90.79293103,
       81.97898954, 47.59226041, 98.80537434])

In [6]:
data[too_fast].size

13

What this is doing is essentially saying: for every element in `too_fast` that is `True`, give me the corresponding element in `arr`. 

Because this is a boolean array, we can also negate it, and pull out all the elements that we consider to be valid reaction times:

In [7]:
data[~too_fast]

array([1668.07869346,  774.38921876, 3161.14983152, ...,  591.4133153 ,
        383.26367525, 1768.50528483])

In [8]:
data[~(data<100)].size

14987

Not only does this *give* you the elements, but modifying those elements will modify the original array, too. In this case, we will set our "too fast" elements to have a value of "not a number", or `NaN`:

In [9]:
data[too_fast] = np.nan
data

array([[1668.07869346,  774.38921876, 3161.14983152, ..., 2359.05394666,
         784.36404676,  448.33416341],
       [2419.38185232,  809.18389145, 2766.62648929, ..., 1159.47379735,
        1330.44887992, 1842.3268586 ],
       [2221.02887591, 1496.00517071,  354.95889145, ..., 1355.74575912,
        1205.29137942, 1385.71283365],
       ...,
       [1654.50469248,  518.3271927 , 5127.58599224, ..., 2544.1042064 ,
         624.07607332, 1029.57386246],
       [ 480.68016502, 4690.12200498, 1520.27397139, ..., 1000.40541618,
         988.73647145,  378.43452948],
       [1823.42891807, 3680.12951133, 3522.94413167, ...,  591.4133153 ,
         383.26367525, 1768.50528483]])

Now, if we try to find which elements are less than 100 milliseconds, we will not find any:

In [10]:
data[data < 100]

array([], dtype=float64)

In [11]:
np.inf *0

nan

<div class="alert alert-warning">Note: You may see a <code>RuntimeWarning</code> when you run the above cell, saying that an "invalid value" was encountered. Sometimes, it is possible for NaNs to appear in an array without your knowledge: for example, if you multiply infinity (<code>np.inf</code>) by zero. So, NumPy is warning us that it has encountered NaNs (the "invalid value") in case we weren't aware. We knew there were NaNs because we put them there, so in this scenario we can safely ignore the warning. <b>However</b>, if you encounter a warning like this in the future and you weren't expecting it, <i>make sure you investigate the source of the warning</i>!
</div>

### Exercise: Threshold (2 points)

<div class="alert alert-success">
Write a function, <code>threshold</code>, which takes an array and returns a new array with values thresholded by the mean of the array.
</div>

In [12]:
def threshold(arr):
    """Computes the mean of the given array, and returns a new array which
    is 1 where values in the original array are greater than the mean, 0 where
    they are equal to the mean, and -1 where they are less than the mean.

    Remember that if you want to create a copy of an array, you need to use
    `arr.copy()`.
    
    Hint: your solution should use boolean indexing.
    
    Parameters
    ----------
    arr : numpy.ndarray

    Returns
    -------
    new_arr : thresholded version of `arr`
    
    """
    ### BEGIN SOLUTION
    dummy1=np.zeros_like(arr)
    dummy1[(arr>arr.mean())]=1
    dummy1[(arr==arr.mean())]=0
    dummy1[(arr<arr.mean())]=-1
    return dummy1

In [13]:
# add your own test cases in this cell!
arr=np.random.randint(1,1000,100).reshape(10,10)
threshold(arr)

array([[ 1,  1,  1, -1, -1,  1, -1, -1, -1,  1],
       [-1, -1,  1,  1, -1, -1, -1,  1, -1, -1],
       [-1,  1, -1,  1, -1, -1, -1, -1, -1,  1],
       [ 1,  1, -1,  1, -1,  1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1,  1,  1,  1,  1,  1],
       [ 1, -1,  1, -1,  1,  1,  1,  1, -1, -1],
       [-1, -1, -1,  1, -1, -1, -1,  1,  1,  1],
       [-1,  1, -1,  1, -1,  1,  1, -1,  1,  1],
       [-1, -1, -1, -1,  1, -1,  1, -1,  1, -1],
       [-1,  1, -1, -1, -1, -1,  1,  1, -1, -1]])

In [14]:
# add your own test cases in this cell!
arr=np.random.random((10,10))
threshold(arr)

array([[ 1., -1., -1.,  1., -1.,  1., -1., -1.,  1.,  1.],
       [ 1.,  1., -1.,  1., -1.,  1., -1., -1.,  1., -1.],
       [-1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1., -1.],
       [ 1.,  1.,  1., -1.,  1., -1., -1.,  1., -1.,  1.],
       [-1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1.,  1.],
       [-1., -1., -1.,  1., -1., -1.,  1., -1., -1., -1.],
       [-1., -1., -1.,  1.,  1., -1., -1.,  1., -1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1.,  1.],
       [-1., -1.,  1., -1., -1.,  1.,  1.,  1.,  1.,  1.],
       [-1.,  1.,  1., -1.,  1.,  1., -1., -1., -1., -1.]])

In [15]:
"""Try a few obvious threshold cases."""
from numpy.testing import assert_array_equal
assert_array_equal(threshold(np.array([1, 1, 1, 1])), np.array([0, 0, 0, 0]))
assert_array_equal(threshold(np.array([1, 0, 1, 0])), np.array([1, -1, 1, -1]))
assert_array_equal(threshold(np.array([1, 0.5, 0, 0.5])), np.array([1, 0, -1, 0]))
assert_array_equal(
    threshold(np.array([[0.5, 0.2, -0.3, 0.1], [1.7, -3.8, 0.5, 0.6]])), 
    np.array([[1, 1, -1, 1], [1, -1, 1, 1]]))
print("These worked! There are a few more in the next cell...")

These worked! There are a few more in the next cell...


In [16]:
"""Make sure a copy of the array is being returned, and that the original array is unmodified."""
x = np.array([[0.5, 0.2, -0.3, 0.1], [1.7, -3.8, 0.5, 0.6]])
y = threshold(x)
assert_array_equal(x, np.array([[0.5, 0.2, -0.3, 0.1], [1.7, -3.8, 0.5, 0.6]]))
assert_array_equal(y, np.array([[1, 1, -1, 1], [1, -1, 1, 1]]))
print("Success!")

Success!


## Array indexing

The other type of fancy indexing is *array indexing*. Let's consider our average response across participants:

In [17]:
data = np.load("experiment_data.npy")
avg_responses = np.mean(data, axis=1)
avg_responses

array([1698.68801725, 1888.71240023, 1796.53362098, 1879.6038851 ,
       1882.53249686, 1824.79568606, 1746.75780815, 1748.55448988,
       1655.75347639, 1740.67757826, 1854.98538242, 1720.70259522,
       1675.2006642 , 1746.52724187, 1768.64738486, 1794.45589925,
       1860.06861469, 1835.73006077, 1520.77977686, 1795.55654863,
       1794.26437533, 1716.73345285, 1740.64166499, 1704.87601852,
       1906.06514665, 1722.68258855, 1857.70131135, 1878.26245376,
       1741.26393398, 1680.21711839, 1830.55940979, 1697.03486501,
       1892.45119973, 1888.69786047, 1653.73721041, 1794.17096019,
       1779.9941148 , 1832.42610672, 1861.63504795, 1685.20108106,
       1652.29647646, 1718.43799102, 1633.30628308, 1686.72435462,
       1810.54490061, 1703.7949561 , 1747.64361845, 1670.90982655,
       1830.47925898, 1771.15425183])

In [18]:
avg_responses.size

50

And let's say we also know which element corresponds to which participant, through the following `participants` array:

In [19]:
participants = np.load("experiment_participants.npy")
participants

array(['p_045', 'p_039', 'p_027', 'p_023', 'p_041', 'p_008', 'p_025',
       'p_019', 'p_036', 'p_049', 'p_050', 'p_029', 'p_032', 'p_006',
       'p_028', 'p_034', 'p_044', 'p_016', 'p_010', 'p_017', 'p_022',
       'p_033', 'p_042', 'p_009', 'p_047', 'p_035', 'p_002', 'p_014',
       'p_020', 'p_043', 'p_003', 'p_012', 'p_030', 'p_015', 'p_011',
       'p_018', 'p_004', 'p_040', 'p_001', 'p_031', 'p_005', 'p_013',
       'p_046', 'p_038', 'p_021', 'p_026', 'p_024', 'p_048', 'p_007',
       'p_037'], dtype='<U5')

In other words, the first element of `avg_responses` corresponds to the first element of `participants` (so participant 45), the second element of `avg_responses` was given by participant 39, and so on.

Let's say we wanted to know what participants had the largest average response, and what participants had the smallest average response. To do this, we might try sorting the responses:

In [20]:
np.sort(avg_responses)

array([1520.77977686, 1633.30628308, 1652.29647646, 1653.73721041,
       1655.75347639, 1670.90982655, 1675.2006642 , 1680.21711839,
       1685.20108106, 1686.72435462, 1697.03486501, 1698.68801725,
       1703.7949561 , 1704.87601852, 1716.73345285, 1718.43799102,
       1720.70259522, 1722.68258855, 1740.64166499, 1740.67757826,
       1741.26393398, 1746.52724187, 1746.75780815, 1747.64361845,
       1748.55448988, 1768.64738486, 1771.15425183, 1779.9941148 ,
       1794.17096019, 1794.26437533, 1794.45589925, 1795.55654863,
       1796.53362098, 1810.54490061, 1824.79568606, 1830.47925898,
       1830.55940979, 1832.42610672, 1835.73006077, 1854.98538242,
       1857.70131135, 1860.06861469, 1861.63504795, 1878.26245376,
       1879.6038851 , 1882.53249686, 1888.69786047, 1888.71240023,
       1892.45119973, 1906.06514665])

However, we then don't know which responses correspond to which trials. A different way to do this would be to use `np.argsort`, which returns an array of indices corresponding to the sorted order of the elements, rather than the elements in sorted order:

In [21]:
np.argsort(avg_responses)

array([18, 42, 40, 34,  8, 47, 12, 29, 39, 43, 31,  0, 45, 23, 21, 41, 11,
       25, 22,  9, 28, 13,  6, 46,  7, 14, 49, 36, 35, 20, 15, 19,  2, 44,
        5, 48, 30, 37, 17, 10, 26, 16, 38, 27,  3,  4, 33,  1, 32, 24],
      dtype=int64)

What this says is that element 18 is the smallest response, element 42 is the next smallest response, and so on, all the way to element 24, which is the largest response:

In [22]:
avg_responses[18]

1520.7797768567086

In [23]:
avg_responses[42]

1633.3062830758922

In [24]:
avg_responses[24]

1906.0651466520821

To use fancy indexing, we can actually use this array of integers as an index. If we use it on the original array, then we will obtain the sorted elements:

In [25]:
avg_responses[np.argsort(avg_responses)]

array([1520.77977686, 1633.30628308, 1652.29647646, 1653.73721041,
       1655.75347639, 1670.90982655, 1675.2006642 , 1680.21711839,
       1685.20108106, 1686.72435462, 1697.03486501, 1698.68801725,
       1703.7949561 , 1704.87601852, 1716.73345285, 1718.43799102,
       1720.70259522, 1722.68258855, 1740.64166499, 1740.67757826,
       1741.26393398, 1746.52724187, 1746.75780815, 1747.64361845,
       1748.55448988, 1768.64738486, 1771.15425183, 1779.9941148 ,
       1794.17096019, 1794.26437533, 1794.45589925, 1795.55654863,
       1796.53362098, 1810.54490061, 1824.79568606, 1830.47925898,
       1830.55940979, 1832.42610672, 1835.73006077, 1854.98538242,
       1857.70131135, 1860.06861469, 1861.63504795, 1878.26245376,
       1879.6038851 , 1882.53249686, 1888.69786047, 1888.71240023,
       1892.45119973, 1906.06514665])

And if we use it on our array of participants, then we can determine what participants had the largest and smallest responses:

In [26]:
participants[np.argsort(avg_responses)]

array(['p_010', 'p_046', 'p_005', 'p_011', 'p_036', 'p_048', 'p_032',
       'p_043', 'p_031', 'p_038', 'p_012', 'p_045', 'p_026', 'p_009',
       'p_033', 'p_013', 'p_029', 'p_035', 'p_042', 'p_049', 'p_020',
       'p_006', 'p_025', 'p_024', 'p_019', 'p_028', 'p_037', 'p_004',
       'p_018', 'p_022', 'p_034', 'p_017', 'p_027', 'p_021', 'p_008',
       'p_007', 'p_003', 'p_040', 'p_016', 'p_050', 'p_002', 'p_044',
       'p_001', 'p_014', 'p_023', 'p_041', 'p_015', 'p_039', 'p_030',
       'p_047'], dtype='<U5')

So, in this case, participant 10 had the smallest average response, while participant 47 had the largest average response.

## From boolean to integer indices

Sometimes, we want to use a combination of boolean and array indexing. For example, if we wanted to pull out just the responses for participant 2, a natural approach would be to use boolean indexing:

In [27]:
participant_2_responses = data[participants == 'p_002']
participant_2_responses

array([[ 1519.95398267,  2268.97864618,  1195.65942267,   504.90066814,
         1801.02089755,   925.24286169,  1810.30761149,  1325.80705157,
         1175.54586424, 10408.41065951,  2455.08935241,   357.09813683,
         1772.0844697 ,  1196.14813706,  8314.75793716,  2675.68801506,
          730.08949799,   425.0148563 ,  2402.60428235,  1428.93884317,
          227.37915983,  1302.38963652,  1593.64880997,  1806.89076956,
         2533.22196284,  1207.73423053,  6303.25912496,  8886.54201129,
          994.92553099,  1713.41231842,   401.87479894,  2505.85572837,
         1952.73193948,   207.56620328,   603.30726209,  3616.1399997 ,
          830.73548608,  1068.04701882,  1469.02747094,  6370.22310164,
          604.55979416,  9081.14741057,  1965.26863145,  3518.87071627,
          517.41562916,  8229.56635964,   461.33763334,   780.20882914,
         1650.10585622,  1314.87174398,  1224.22622967,  2083.55702061,
         2968.86713293,  1869.42631685,  1111.82126554,  1948.83

Another way that we could do this would be to determine the *index* of participant 2, and then use that to index into `data`. To do this, we can use a function called `np.argwhere`, which returns the indices of elements that are true:

In [28]:
participants = np.load("experiment_participants.npy")
np.argwhere(participants == 'p_002')

array([[26]], dtype=int64)

In [29]:
data[26]

array([ 1519.95398267,  2268.97864618,  1195.65942267,   504.90066814,
        1801.02089755,   925.24286169,  1810.30761149,  1325.80705157,
        1175.54586424, 10408.41065951,  2455.08935241,   357.09813683,
        1772.0844697 ,  1196.14813706,  8314.75793716,  2675.68801506,
         730.08949799,   425.0148563 ,  2402.60428235,  1428.93884317,
         227.37915983,  1302.38963652,  1593.64880997,  1806.89076956,
        2533.22196284,  1207.73423053,  6303.25912496,  8886.54201129,
         994.92553099,  1713.41231842,   401.87479894,  2505.85572837,
        1952.73193948,   207.56620328,   603.30726209,  3616.1399997 ,
         830.73548608,  1068.04701882,  1469.02747094,  6370.22310164,
         604.55979416,  9081.14741057,  1965.26863145,  3518.87071627,
         517.41562916,  8229.56635964,   461.33763334,   780.20882914,
        1650.10585622,  1314.87174398,  1224.22622967,  2083.55702061,
        2968.86713293,  1869.42631685,  1111.82126554,  1948.83806694,
      

So in this case, we see that participant 2 corresponds to index 26.

### Exercise: Averaging responses (2 points)

<div class="alert alert-success">
Write a function that takes as arguments a participant id, the data, and the list of participant names, and computes the average response for the given participant.
</div>

In [30]:
def participant_mean(participant, data, participants):
    """Computes the mean response for the given participant. A clear statement
    describing the problem should be printed if more than one participant has the given name.
    
    Hint: your solution should use `np.argwhere`.
    
    Parameters
    ----------
    participant: string
        The name/id of the participant
    data: numpy.ndarray with shape (n, m)
        Rows correspond to participants, columns to trials
    participants: numpy.ndarray with shape(n,)
        A string array containing participant names/ids, corresponding to
        the rows of the `data` array.
        
    Returns
    -------
    float: the mean response of the participant over all trials
    
    """
    ### BEGIN SOLUTION
    return np.mean(np.mean(data,axis=1)[np.argwhere(participants==participant)])

In [31]:
data = np.load("experiment_data.npy")
participants = np.load("experiment_participants.npy")
np.argwhere(participants=="p_003")

array([[30]], dtype=int64)

In [32]:
# add your own test cases in this cell!
participant_mean("p_003",data,participants)

1830.559409791249

In [33]:
"""Check for correct answers with the example experiment data."""
from numpy.testing import assert_allclose
data = np.load("experiment_data.npy")
participants = np.load("experiment_participants.npy")
assert_allclose(participant_mean('p_002', data, participants), 1857.7013113499095)
assert_allclose(participant_mean('p_047', data, participants), 1906.0651466520821)
assert_allclose(participant_mean('p_013', data, participants), 1718.4379910225193)
print("These work! More in next cell...")

These work! More in next cell...


In [34]:
"""Check for correct answers for some different data."""
data = np.arange(32).reshape((4, 8))
participants = np.array(['a', 'b', 'c', 'd'])
assert_allclose(participant_mean('a', data, participants), 3.5)
assert_allclose(participant_mean('b', data, participants), 11.5)
assert_allclose(participant_mean('c', data, participants), 19.5)
assert_allclose(participant_mean('d', data, participants), 27.5)
print("Success!")

Success!
